name: "Hello Actions"
description: "Greet Someone"
author: "silwal.pradip@outlook.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  
  runs:
    using: "docker"
    image: "Dockerfile"

  branding:
    icon: "mic"
    color: "purple"